# Makefile generated by the project manager
#


# GENERATED: Wed Apr 02 11:51:17  IST IST 2014
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = New_kernel.wpj
PRJ_FULL_PATH  = /home/kartha/programs/VxWorks/New_kernel
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o timer.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      =  $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(TGT_DIR)/config/linux
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

ifeq ($(BUILD_SPEC),default)
CPU            = SIMLINUX
TOOL           = diab
TOOL_FAMILY    = diab
DEFAULT_RULE   = vxWorks
OPT            = -inet6
VXBUILD        = AMP
endif

ifeq ($(BUILD_SPEC),default_rom)
CPU            = SIMLINUX
TOOL           = diab
TOOL_FAMILY    = diab
DEFAULT_RULE   = vxWorks_rom
OPT            = -inet6
VXBUILD        = AMP
endif

ifeq ($(BUILD_SPEC),default_romCompress)
CPU            = SIMLINUX
TOOL           = diab
TOOL_FAMILY    = diab
DEFAULT_RULE   = vxWorks_romCompress
OPT            = -inet6
VXBUILD        = AMP
endif

ifeq ($(BUILD_SPEC),default_romResident)
CPU            = SIMLINUX
TOOL           = diab
TOOL_FAMILY    = diab
DEFAULT_RULE   = vxWorks_romResident
OPT            = -inet6
VXBUILD        = AMP
endif


## Memory adresses variables

RAM_LOW_ADRS = 60010000
RAM_HIGH_ADRS = ffffffff
LOCAL_MEM_LOCAL_ADRS = 60000000

## component-configuration info

COMPONENTS = INCLUDE_ADR_SPACE_LIB \
	INCLUDE_ADR_SPACE_SHELL_CMD \
	INCLUDE_ADR_SPACE_SHOW \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ATOMIC_OPERATORS \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BMPLIB \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSP_MACROS \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CHECKSUM \
	INCLUDE_CLASS_LIB \
	INCLUDE_CLASS_LIST \
	INCLUDE_CLASS_SHOW \
	INCLUDE_COMMON_NET \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CPLUS \
	INCLUDE_CPLUS_DEMANGLER \
	INCLUDE_CPLUS_LANG \
	INCLUDE_CPU_LIGHT_PWR_MGR \
	INCLUDE_CPU_PWR_MGMT \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DEBUG \
	INCLUDE_DEBUG_SHELL_CMD \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DIAB_INTRINSICS \
	INCLUDE_DISK_UTIL \
	INCLUDE_DISK_UTIL_SHELL_CMD \
	INCLUDE_DLL \
	INCLUDE_EDR_ERRLOG \
	INCLUDE_EDR_PM \
	INCLUDE_EDR_SHELL_CMD \
	INCLUDE_EDR_SHOW \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_END \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_SHOW \
	INCLUDE_EXC_TASK \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_FTP \
	INCLUDE_GETADDRINFO_SYSCTL \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HOOKS \
	INCLUDE_HOOK_SHOW \
	INCLUDE_HOST_TBL \
	INCLUDE_HOST_TBL_SYSCTL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP \
	INCLUDE_HW_FP_MREGS \
	INCLUDE_HW_FP_SHOW \
	INCLUDE_INTCTLR_LIB \
	INCLUDE_IO_BASIC \
	INCLUDE_IO_FILE_SYSTEM \
	INCLUDE_IO_MISC \
	INCLUDE_IO_POSIX \
	INCLUDE_IO_REMOVABLE \
	INCLUDE_IO_RTP \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPAIP \
	INCLUDE_IPAIP_GLOBAL_CONFIGS \
	INCLUDE_IPCOM \
	INCLUDE_IPCOM_SHELL_CMD \
	INCLUDE_IPCOM_USE_ETHERNET \
	INCLUDE_IPCOM_USE_INET \
	INCLUDE_IPCOM_USE_INET6 \
	INCLUDE_IPIFCONFIG_CMD \
	INCLUDE_IPNET \
	INCLUDE_IPNET_IFCONFIG_1 \
	INCLUDE_IPNET_LOOPBACK_CONFIG \
	INCLUDE_IPNET_PACKET_POOL_11 \
	INCLUDE_IPNET_PACKET_POOL_3 \
	INCLUDE_IPNET_PACKET_POOL_4 \
	INCLUDE_IPNET_PACKET_POOL_5 \
	INCLUDE_IPNET_PACKET_POOL_6 \
	INCLUDE_IPNET_SOCKET \
	INCLUDE_IPNET_STACK \
	INCLUDE_IPNET_SYSCTL \
	INCLUDE_IPNET_USE_LOOPBACK \
	INCLUDE_IPNET_USE_PACKET_POOL \
	INCLUDE_IPNET_USE_ROUTESOCK \
	INCLUDE_IPNET_USE_SOCK_COMPAT \
	INCLUDE_IPPROXYARP \
	INCLUDE_IPRADVD \
	INCLUDE_IPSYSCTL_CMD \
	INCLUDE_IPTCP \
	INCLUDE_IPV4 \
	INCLUDE_IPV6 \
	INCLUDE_IPWRAP_GETADDRINFO \
	INCLUDE_IPWRAP_IFCONFIG \
	INCLUDE_IPWRAP_INETLIB \
	INCLUDE_IPWRAP_IPPROTO \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_KERNEL_HARDENING \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOADER_HOOKS \
	INCLUDE_LOGGING \
	INCLUDE_LSTLIB \
	INCLUDE_MBUF_UTIL1 \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MEM_MGR_INFO \
	INCLUDE_MEM_RTP \
	INCLUDE_MEM_SHOW \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MODULE_SHELL_CMD \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MSG_Q_OPEN \
	INCLUDE_MSG_Q_SHOW \
	INCLUDE_MUX \
	INCLUDE_NBIO_LOG \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETPOOLSHOW \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_DRV \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_REM_IO \
	INCLUDE_NET_SYSCTL \
	INCLUDE_NULLBUFPOOL \
	INCLUDE_OBJ_INFO \
	INCLUDE_OBJ_LIB \
	INCLUDE_OBJ_OPEN \
	INCLUDE_OBJ_OWNERSHIP \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_PASSFS \
	INCLUDE_PASSFS_SYM_TBL \
	INCLUDE_PG_MGR_LIB \
	INCLUDE_PG_MGR_SHOW \
	INCLUDE_PG_POOL_LIB \
	INCLUDE_PG_POOL_PHYS_LIB \
	INCLUDE_PG_POOL_SHOW \
	INCLUDE_PG_POOL_VIRT_LIB \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_AIO \
	INCLUDE_POSIX_AIO_SHOW \
	INCLUDE_POSIX_AIO_SYSDRV \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_POSIX_FTRUNC \
	INCLUDE_POSIX_MEM \
	INCLUDE_POSIX_MQ \
	INCLUDE_POSIX_MQ_SHOW \
	INCLUDE_POSIX_PTHREADS \
	INCLUDE_POSIX_SCHED \
	INCLUDE_POSIX_SEM \
	INCLUDE_POSIX_SEM_SHOW \
	INCLUDE_POSIX_SIGNALS \
	INCLUDE_POSIX_TIMERS \
	INCLUDE_POSIX_TIMER_SHOW \
	INCLUDE_PROTECT_INTERRUPT_STACK \
	INCLUDE_PROTECT_TASK_STACK \
	INCLUDE_PROTECT_TEXT \
	INCLUDE_PROTECT_VEC_TABLE \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_LIB \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAM_DISK \
	INCLUDE_RAWFS \
	INCLUDE_RBUFF \
	INCLUDE_RBUFF_SHOW \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_REMLIB \
	INCLUDE_REMLIB_SYSCTL \
	INCLUDE_RNG_BUF \
	INCLUDE_ROMFS \
	INCLUDE_RTP \
	INCLUDE_RTP_APPL_INIT_BOOTLINE \
	INCLUDE_RTP_ARCH \
	INCLUDE_RTP_DEBUG \
	INCLUDE_RTP_HOOKS \
	INCLUDE_RTP_SHELL_C \
	INCLUDE_RTP_SHELL_CMD \
	INCLUDE_RTP_SHOW \
	INCLUDE_RTP_SHOW_SHELL_CMD \
	INCLUDE_SC_IOS \
	INCLUDE_SC_KERNEL \
	INCLUDE_SC_MMAN \
	INCLUDE_SC_POSIX \
	INCLUDE_SC_SD \
	INCLUDE_SC_SHL \
	INCLUDE_SC_SOCKLIB \
	INCLUDE_SC_SYSCTL \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_EXCHANGE \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SEM_OPEN \
	INCLUDE_SEM_READ_WRITE \
	INCLUDE_SEM_READ_WRITE_CREATE \
	INCLUDE_SEM_SHOW \
	INCLUDE_SET \
	INCLUDE_SHARED_DATA \
	INCLUDE_SHARED_DATA_SHOW \
	INCLUDE_SHARED_DATA_SHOW_SHELL_CMD \
	INCLUDE_SHELL \
	INCLUDE_SHELL_BANNER \
	INCLUDE_SHELL_CORE \
	INCLUDE_SHELL_EMACS_MODE \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_INTERP_CMD \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SHL \
	INCLUDE_SHL_SHELL_CMD \
	INCLUDE_SHL_SHOW \
	INCLUDE_SHOW_ROUTINES \
	INCLUDE_SIGEVENT \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPINLOCK \
	INCLUDE_STARTUP_SCRIPT \
	INCLUDE_STAT_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_STDIO_SHOW \
	INCLUDE_SYM_SHELL_CMD \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCALL_HOOKS \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSCTL \
	INCLUDE_SYSCTL_HW \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYS_START \
	INCLUDE_SYS_TIMESTAMP \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_HOOKS_SHOW \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_LIST \
	INCLUDE_TASK_OPEN \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHELL_CMD \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_STACK_NO_EXEC \
	INCLUDE_TASK_VARS \
	INCLUDE_TIMER_OPEN \
	INCLUDE_TIMER_SYS \
	INCLUDE_TIMESTAMP \
	INCLUDE_TIMEX \
	INCLUDE_TLS \
	INCLUDE_TLS_LOADER_SUPPORT \
	INCLUDE_TRIGGERING \
	INCLUDE_TRIGGER_SHOW \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UNLOADER \
	INCLUDE_UNLOADER_SHELL_CMD \
	INCLUDE_USER_APPL \
	INCLUDE_VIRTUAL_DISK \
	INCLUDE_VM_INVTBL \
	INCLUDE_VM_RTP \
	INCLUDE_VM_SHOW \
	INCLUDE_VM_SHOW_SHELL_CMD \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_DEVICE_CONNECT \
	INCLUDE_VXBUS_DEV_INIT \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXBUS_SHOW \
	INCLUDE_VXEVENTS \
	INCLUDE_VXIPI \
	INCLUDE_VXMEMPROBE_INIT \
	INCLUDE_VXSIM_IFCONFIG \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WATCHDOGS_SHOW \
	INCLUDE_WB_RUNTIME_SUPPORT \
	INCLUDE_WDB \
	INCLUDE_WDB_BANNER \
	INCLUDE_WDB_BP \
	INCLUDE_WDB_BP_SYNC \
	INCLUDE_WDB_COMM_PIPE \
	INCLUDE_WDB_CTXT \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTPOINTS \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_EXC_NOTIFY \
	INCLUDE_WDB_EXIT_NOTIFY \
	INCLUDE_WDB_FUNC_CALL \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_MEM \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_REG \
	INCLUDE_WDB_RTP \
	INCLUDE_WDB_RTP_BP \
	INCLUDE_WDB_RTP_CONTROL \
	INCLUDE_WDB_START_NOTIFY \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_BP \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TASK_REG \
	INCLUDE_WDB_TSFS \
	INCLUDE_WDB_USER_EVENT \
	INCLUDE_WDB_VIO \
	INCLUDE_WDB_VIO_LIB \
	INCLUDE_WINDVIEW \
	INCLUDE_WINDVIEW_CLASS \
	INCLUDE_WVUPLOAD_FILE \
	INCLUDE_WVUPLOAD_TSFSSOCK \
	INCLUDE_XBD \
	INCLUDE_XBD_RAMDRV

MANAGED_LIBS = libspl.a libtipc.a
COMPONENT_LIBS = libspl.a

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AR               = dar
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CC_ARCH_SPEC     = -tX86LH:vxworks66
CFLAGS           = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS        = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS_PROJECT = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -D_WRS_VX_AMP
CFLAGS_PROJECT   = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -D_WRS_VX_AMP
CPP              = dcc -E -Xpreprocessor-lineno-off
DOC_FILES        = sysLib simSio hostSio simnetEnd
EXTRA_MODULES    = $(SUB_TARGETS)
LD               = dld
LDFLAGS          = -tX86LH:vxworks66 -X -N -Xgenerate-paddr
LD_LINK_PATH     = -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab_standard -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab -L$(TGT_DIR)/lib/simlinux/SIMLINUX/common -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common
LD_PARTIAL       = dld -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LD_PARTIAL_FLAGS = -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LIBS             = $(VX_OS_LIBS)
NM               = ddump -Ng -g
OPT              = -inet6
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -Xmake-dependency -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
RELEASE_CMD      = vxWorks vxWorks.st
SIZE             = ddump -Z
TOOL_FAMILY      = diab
VXBUILD          = AMP
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AR               = dar
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CC_ARCH_SPEC     = -tX86LH:vxworks66
CFLAGS           = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS        = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS_PROJECT = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -D_WRS_VX_AMP
CFLAGS_PROJECT   = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -D_WRS_VX_AMP
CPP              = dcc -E -Xpreprocessor-lineno-off
DOC_FILES        = sysLib simSio hostSio simnetEnd
EXTRA_MODULES    = $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = dld
LDFLAGS          = -tX86LH:vxworks66 -X -N -Xgenerate-paddr
LD_LINK_PATH     = -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab_standard -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab -L$(TGT_DIR)/lib/simlinux/SIMLINUX/common -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common
LD_PARTIAL       = dld -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LD_PARTIAL_FLAGS = -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LIBS             = $(VX_OS_LIBS)
NM               = ddump -Ng -g
OPT              = -inet6
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -Xmake-dependency -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
RELEASE_CMD      = vxWorks vxWorks.st
SIZE             = ddump -Z
TOOL_FAMILY      = diab
VXBUILD          = AMP
ROM_TEXT_ADRS    = 
ROM_SIZE         = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AR               = dar
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CC_ARCH_SPEC     = -tX86LH:vxworks66
CFLAGS           = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS        = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS_PROJECT = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -D_WRS_VX_AMP
CFLAGS_PROJECT   = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -D_WRS_VX_AMP
CPP              = dcc -E -Xpreprocessor-lineno-off
DOC_FILES        = sysLib simSio hostSio simnetEnd
EXTRA_MODULES    = $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = dld
LDFLAGS          = -tX86LH:vxworks66 -X -N -Xgenerate-paddr
LD_LINK_PATH     = -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab_standard -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab -L$(TGT_DIR)/lib/simlinux/SIMLINUX/common -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common
LD_PARTIAL       = dld -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LD_PARTIAL_FLAGS = -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LIBS             = $(VX_OS_LIBS)
NM               = ddump -Ng -g
OPT              = -inet6
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -Xmake-dependency -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
RELEASE_CMD      = vxWorks vxWorks.st
SIZE             = ddump -Z
TOOL_FAMILY      = diab
VXBUILD          = AMP
ROM_TEXT_ADRS    = 
ROM_SIZE         = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AR               = dar
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CC_ARCH_SPEC     = -tX86LH:vxworks66
CFLAGS           = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS        = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -I$(PRJ_DIR) -I$(TGT_DIR)/config/linux -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6
CFLAGS_AS_PROJECT = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xmnem-mit -c -D_WRS_VX_AMP
CFLAGS_PROJECT   = -g -tX86LH:vxworks66 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -Xlint -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.6/osconfig/vxworks/h @./ipcom_ipdomain-inet6 -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=SIMLINUX -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DIP_PORT_VXWORKS=66 -DINET -DINET6 -DINET6 -D_WRS_VX_AMP
CPP              = dcc -E -Xpreprocessor-lineno-off
DOC_FILES        = sysLib simSio hostSio simnetEnd
EXTRA_MODULES    = $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = dld
LDFLAGS          = -tX86LH:vxworks66 -X -N -Xgenerate-paddr
LD_LINK_PATH     = -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab_standard -L$(TGT_DIR)/lib/simlinux/SIMLINUX/diab -L$(TGT_DIR)/lib/simlinux/SIMLINUX/common -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/diab -L$(WIND_HOME)/components/obj/vxworks-6.6/krnl/lib/simlinux/SIMLINUX/common
LD_PARTIAL       = dld -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LD_PARTIAL_FLAGS = -tX86LH:vxworks66 -X -r5 -f 0x90,1,1
LIBS             = $(VX_OS_LIBS)
NM               = ddump -Ng -g
OPT              = -inet6
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -Xmake-dependency -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
RELEASE_CMD      = vxWorks vxWorks.st
SIZE             = ddump -Z
TOOL_FAMILY      = diab
VXBUILD          = AMP
ROM_TEXT_ADRS    = 
ROM_SIZE         = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

sysALib.o: $(PRJ_DIR)/prjParams.h

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

timer.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/timer.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

timer.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/timer.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

timer.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/timer.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

timer.o:
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/timer.c
endif


## user defined rules

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

sysLib.o : $(TGT_DIR)/config/linux/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/linux/sysLib.c -o $@

sysALib.o : $(TGT_DIR)/config/linux/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/linux/sysALib.s -o $@

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
