/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Thu Mar 27 09:31:21  IST IST 2014
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ADR_SPACE_LIB
#define INCLUDE_ADR_SPACE_SHELL_CMD
#define INCLUDE_ADR_SPACE_SHOW
#define INCLUDE_ANSI_ABORT
#define INCLUDE_ANSI_ABS
#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_ATOF
#define INCLUDE_ANSI_BSEARCH
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_LONGJMP
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_MEMCHR
#define INCLUDE_ANSI_MEMCMP
#define INCLUDE_ANSI_MEMCPY
#define INCLUDE_ANSI_MEMMOVE
#define INCLUDE_ANSI_MEMSET
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDIO_EXTRA
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STDLIB_NUMBERS
#define INCLUDE_ANSI_STRCASECMP
#define INCLUDE_ANSI_STRCAT
#define INCLUDE_ANSI_STRCMP
#define INCLUDE_ANSI_STRCPY
#define INCLUDE_ANSI_STRDUP
#define INCLUDE_ANSI_STRERROR
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_STRLCPY
#define INCLUDE_ANSI_STRLEN
#define INCLUDE_ANSI_STRNCASECMP
#define INCLUDE_ANSI_STRNCAT
#define INCLUDE_ANSI_STRNCMP
#define INCLUDE_ANSI_STRNCPY
#define INCLUDE_ANSI_STRTOD
#define INCLUDE_ANSI_TIME
#define INCLUDE_APPL_LOG_UTIL
#define INCLUDE_ATOMIC_OPERATORS
#define INCLUDE_AVL_UINT_TREES
#define INCLUDE_BASE_KERNEL
#define INCLUDE_BLIB
#define INCLUDE_BMPLIB
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BSP_MACROS
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CHECKSUM
#define INCLUDE_CLASS_LIB
#define INCLUDE_CLASS_LIST
#define INCLUDE_CLASS_SHOW
#define INCLUDE_COMMON_NET
#define INCLUDE_COPROCESSOR
#define INCLUDE_COPROCESSOR_SHOW
#define INCLUDE_CPLUS
#define INCLUDE_CPLUS_DEMANGLER
#define INCLUDE_CPLUS_LANG
#define INCLUDE_CPU_LIGHT_PWR_MGR
#define INCLUDE_CPU_PWR_MGMT
#define INCLUDE_CTORS_DTORS
#define INCLUDE_DEBUG
#define INCLUDE_DEBUG_SHELL_CMD
#define INCLUDE_DEVICE_MANAGER
#define INCLUDE_DIAB_INTRINSICS
#define INCLUDE_DISK_UTIL
#define INCLUDE_DISK_UTIL_SHELL_CMD
#define INCLUDE_DLL
#define INCLUDE_EDR_ERRLOG
#define INCLUDE_EDR_PM
#define INCLUDE_EDR_SHELL_CMD
#define INCLUDE_EDR_SHOW
#define INCLUDE_EDR_STUB
#define INCLUDE_EDR_SYSDBG_FLAG
#define INCLUDE_END
#define INCLUDE_ENV_VARS
#define INCLUDE_ERF
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_SHOW
#define INCLUDE_EXC_TASK
#define INCLUDE_FLOATING_POINT
#define INCLUDE_FORMATTED_IO
#define INCLUDE_FORMATTED_OUT_BASIC
#define INCLUDE_FP_TYPE
#define INCLUDE_FS_EVENT_UTIL
#define INCLUDE_FS_MONITOR
#define INCLUDE_FTP
#define INCLUDE_GETADDRINFO_SYSCTL
#define INCLUDE_HANDLE_SHOW
#define INCLUDE_HASH
#define INCLUDE_HOOKS
#define INCLUDE_HOOK_SHOW
#define INCLUDE_HOST_TBL
#define INCLUDE_HOST_TBL_SYSCTL
#define INCLUDE_HWMEM_ALLOC
#define INCLUDE_HW_FP
#define INCLUDE_HW_FP_MREGS
#define INCLUDE_HW_FP_SHOW
#define INCLUDE_INTCTLR_LIB
#define INCLUDE_IO_BASIC
#define INCLUDE_IO_FILE_SYSTEM
#define INCLUDE_IO_MISC
#define INCLUDE_IO_POSIX
#define INCLUDE_IO_REMOVABLE
#define INCLUDE_IO_RTP
#define INCLUDE_IO_SYSTEM
#define INCLUDE_IPAIP
#define INCLUDE_IPAIP_GLOBAL_CONFIGS
#define INCLUDE_IPCOM
#define INCLUDE_IPCOM_SHELL_CMD
#define INCLUDE_IPCOM_USE_ETHERNET
#define INCLUDE_IPCOM_USE_INET
#define INCLUDE_IPCOM_USE_INET6
#define INCLUDE_IPIFCONFIG_CMD
#define INCLUDE_IPNET
#define INCLUDE_IPNET_IFCONFIG_1
#define INCLUDE_IPNET_LOOPBACK_CONFIG
#define INCLUDE_IPNET_PACKET_POOL_11
#define INCLUDE_IPNET_PACKET_POOL_3
#define INCLUDE_IPNET_PACKET_POOL_4
#define INCLUDE_IPNET_PACKET_POOL_5
#define INCLUDE_IPNET_PACKET_POOL_6
#define INCLUDE_IPNET_SOCKET
#define INCLUDE_IPNET_STACK
#define INCLUDE_IPNET_SYSCTL
#define INCLUDE_IPNET_USE_LOOPBACK
#define INCLUDE_IPNET_USE_PACKET_POOL
#define INCLUDE_IPNET_USE_ROUTESOCK
#define INCLUDE_IPNET_USE_SOCK_COMPAT
#define INCLUDE_IPPROXYARP
#define INCLUDE_IPRADVD
#define INCLUDE_IPSYSCTL_CMD
#define INCLUDE_IPTCP
#define INCLUDE_IPV4
#define INCLUDE_IPV6
#define INCLUDE_IPWRAP_GETADDRINFO
#define INCLUDE_IPWRAP_IFCONFIG
#define INCLUDE_IPWRAP_INETLIB
#define INCLUDE_IPWRAP_IPPROTO
#define INCLUDE_JOB_QUEUE
#define INCLUDE_JOB_TASK
#define INCLUDE_KERNEL
#define INCLUDE_KERNEL_ARCH
#define INCLUDE_KERNEL_HARDENING
#define INCLUDE_LINKBUFPOOL
#define INCLUDE_LOADER
#define INCLUDE_LOADER_CODE
#define INCLUDE_LOADER_HOOKS
#define INCLUDE_LOGGING
#define INCLUDE_LSTLIB
#define INCLUDE_MBUF_UTIL1
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MEM_MGR_INFO
#define INCLUDE_MEM_RTP
#define INCLUDE_MEM_SHOW
#define INCLUDE_MMU_BASIC
#define INCLUDE_MMU_GLOBAL_MAP
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MODULE_SHELL_CMD
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_CREATE_DELETE
#define INCLUDE_MSG_Q_EVENTS
#define INCLUDE_MSG_Q_INFO
#define INCLUDE_MSG_Q_OPEN
#define INCLUDE_MSG_Q_SHOW
#define INCLUDE_MUX
#define INCLUDE_NBIO_LOG
#define INCLUDE_NETBUFLIB
#define INCLUDE_NETBUFPOOL
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETPOOLSHOW
#define INCLUDE_NETWORK
#define INCLUDE_NET_BOOT
#define INCLUDE_NET_DAEMON
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SYSCTL
#define INCLUDE_NULLBUFPOOL
#define INCLUDE_OBJ_INFO
#define INCLUDE_OBJ_LIB
#define INCLUDE_OBJ_OPEN
#define INCLUDE_OBJ_OWNERSHIP
#define INCLUDE_OFFSET_SYMBOLS
#define INCLUDE_PASSFS
#define INCLUDE_PASSFS_SYM_TBL
#define INCLUDE_PG_MGR_LIB
#define INCLUDE_PG_MGR_SHOW
#define INCLUDE_PG_POOL_LIB
#define INCLUDE_PG_POOL_PHYS_LIB
#define INCLUDE_PG_POOL_SHOW
#define INCLUDE_PG_POOL_VIRT_LIB
#define INCLUDE_PIPES
#define INCLUDE_PLB_BUS
#define INCLUDE_POOL
#define INCLUDE_POSIX_AIO
#define INCLUDE_POSIX_AIO_SHOW
#define INCLUDE_POSIX_AIO_SYSDRV
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_POSIX_DIRLIB
#define INCLUDE_POSIX_FS
#define INCLUDE_POSIX_FTRUNC
#define INCLUDE_POSIX_MEM
#define INCLUDE_POSIX_MQ
#define INCLUDE_POSIX_MQ_SHOW
#define INCLUDE_POSIX_PTHREADS
#define INCLUDE_POSIX_SCHED
#define INCLUDE_POSIX_SEM
#define INCLUDE_POSIX_SEM_SHOW
#define INCLUDE_POSIX_SIGNALS
#define INCLUDE_POSIX_TIMERS
#define INCLUDE_POSIX_TIMER_SHOW
#define INCLUDE_PROTECT_INTERRUPT_STACK
#define INCLUDE_PROTECT_TASK_STACK
#define INCLUDE_PROTECT_TEXT
#define INCLUDE_PROTECT_VEC_TABLE
#define INCLUDE_PTYDRV
#define INCLUDE_Q_FIFO
#define INCLUDE_Q_LIB
#define INCLUDE_Q_PRI_BMAP
#define INCLUDE_Q_PRI_DELTA
#define INCLUDE_Q_PRI_LIST
#define INCLUDE_RAM_DISK
#define INCLUDE_RAWFS
#define INCLUDE_RBUFF
#define INCLUDE_RBUFF_SHOW
#define INCLUDE_REBOOT_HOOKS
#define INCLUDE_REMLIB
#define INCLUDE_REMLIB_SYSCTL
#define INCLUDE_RNG_BUF
#define INCLUDE_ROMFS
#define INCLUDE_RTP
#define INCLUDE_RTP_APPL_INIT_BOOTLINE
#define INCLUDE_RTP_ARCH
#define INCLUDE_RTP_DEBUG
#define INCLUDE_RTP_HOOKS
#define INCLUDE_RTP_SHELL_C
#define INCLUDE_RTP_SHELL_CMD
#define INCLUDE_RTP_SHOW
#define INCLUDE_RTP_SHOW_SHELL_CMD
#define INCLUDE_SC_IOS
#define INCLUDE_SC_KERNEL
#define INCLUDE_SC_MMAN
#define INCLUDE_SC_POSIX
#define INCLUDE_SC_SD
#define INCLUDE_SC_SHL
#define INCLUDE_SC_SOCKLIB
#define INCLUDE_SC_SYSCTL
#define INCLUDE_SELECT
#define INCLUDE_SELECT_SUPPORT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_BINARY_CREATE
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_COUNTING_CREATE
#define INCLUDE_SEM_DELETE
#define INCLUDE_SEM_EVENTS
#define INCLUDE_SEM_EXCHANGE
#define INCLUDE_SEM_INFO
#define INCLUDE_SEM_LIB
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEM_MUTEX_CREATE
#define INCLUDE_SEM_OPEN
#define INCLUDE_SEM_READ_WRITE
#define INCLUDE_SEM_READ_WRITE_CREATE
#define INCLUDE_SEM_SHOW
#define INCLUDE_SET
#define INCLUDE_SHARED_DATA
#define INCLUDE_SHARED_DATA_SHOW
#define INCLUDE_SHARED_DATA_SHOW_SHELL_CMD
#define INCLUDE_SHELL
#define INCLUDE_SHELL_BANNER
#define INCLUDE_SHELL_CORE
#define INCLUDE_SHELL_EMACS_MODE
#define INCLUDE_SHELL_INTERP_C
#define INCLUDE_SHELL_INTERP_CMD
#define INCLUDE_SHELL_VI_MODE
#define INCLUDE_SHL
#define INCLUDE_SHL_SHELL_CMD
#define INCLUDE_SHL_SHOW
#define INCLUDE_SHOW_ROUTINES
#define INCLUDE_SIGEVENT
#define INCLUDE_SIGNALS
#define INCLUDE_SIGNAL_ARCH
#define INCLUDE_SIO
#define INCLUDE_SLL
#define INCLUDE_SOCKLIB
#define INCLUDE_SPINLOCK
#define INCLUDE_STARTUP_SCRIPT
#define INCLUDE_STAT_SYM_TBL
#define INCLUDE_STDIO
#define INCLUDE_STDIO_SHOW
#define INCLUDE_SYM_SHELL_CMD
#define INCLUDE_SYM_TBL
#define INCLUDE_SYM_TBL_INIT
#define INCLUDE_SYM_TBL_SHOW
#define INCLUDE_SYSCALL_HOOKS
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSCTL
#define INCLUDE_SYSCTL_HW
#define INCLUDE_SYSHW_INIT
#define INCLUDE_SYS_START
#define INCLUDE_SYS_TIMESTAMP
#define INCLUDE_TASK_CREATE_DELETE
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_HOOKS_SHOW
#define INCLUDE_TASK_INFO
#define INCLUDE_TASK_LIST
#define INCLUDE_TASK_OPEN
#define INCLUDE_TASK_RESTART
#define INCLUDE_TASK_SHELL_CMD
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_STACK_NO_EXEC
#define INCLUDE_TASK_VARS
#define INCLUDE_TIMER_OPEN
#define INCLUDE_TIMER_SYS
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIMEX
#define INCLUDE_TLS
#define INCLUDE_TLS_LOADER_SUPPORT
#define INCLUDE_TRIGGERING
#define INCLUDE_TRIGGER_SHOW
#define INCLUDE_TTY_DEV
#define INCLUDE_TYLIB
#define INCLUDE_UNLOADER
#define INCLUDE_UNLOADER_SHELL_CMD
#define INCLUDE_USER_APPL
#define INCLUDE_VIRTUAL_DISK
#define INCLUDE_VM_INVTBL
#define INCLUDE_VM_RTP
#define INCLUDE_VM_SHOW
#define INCLUDE_VM_SHOW_SHELL_CMD
#define INCLUDE_VXBUS
#define INCLUDE_VXBUS_ACTIVATE
#define INCLUDE_VXBUS_DEVICE_CONNECT
#define INCLUDE_VXBUS_DEV_INIT
#define INCLUDE_VXBUS_INIT
#define INCLUDE_VXBUS_SHOW
#define INCLUDE_VXEVENTS
#define INCLUDE_VXIPI
#define INCLUDE_VXMEMPROBE_INIT
#define INCLUDE_VXSIM_IFCONFIG
#define INCLUDE_VX_TRADITIONAL_SCHEDULER
#define INCLUDE_WATCHDOGS
#define INCLUDE_WATCHDOGS_CREATE_DELETE
#define INCLUDE_WATCHDOGS_SHOW
#define INCLUDE_WB_RUNTIME_SUPPORT
#define INCLUDE_WDB
#define INCLUDE_WDB_BANNER
#define INCLUDE_WDB_BP
#define INCLUDE_WDB_BP_SYNC
#define INCLUDE_WDB_COMM_PIPE
#define INCLUDE_WDB_CTXT
#define INCLUDE_WDB_DIRECT_CALL
#define INCLUDE_WDB_EVENTPOINTS
#define INCLUDE_WDB_EVENTS
#define INCLUDE_WDB_EXC_NOTIFY
#define INCLUDE_WDB_EXIT_NOTIFY
#define INCLUDE_WDB_FUNC_CALL
#define INCLUDE_WDB_GOPHER
#define INCLUDE_WDB_MDL_SYM_SYNC
#define INCLUDE_WDB_MEM
#define INCLUDE_WDB_POST_KERNEL_INIT
#define INCLUDE_WDB_REG
#define INCLUDE_WDB_RTP
#define INCLUDE_WDB_RTP_BP
#define INCLUDE_WDB_RTP_CONTROL
#define INCLUDE_WDB_START_NOTIFY
#define INCLUDE_WDB_TASK
#define INCLUDE_WDB_TASK_BP
#define INCLUDE_WDB_TASK_HOOKS
#define INCLUDE_WDB_TASK_REG
#define INCLUDE_WDB_TSFS
#define INCLUDE_WDB_USER_EVENT
#define INCLUDE_WDB_VIO
#define INCLUDE_WDB_VIO_LIB
#define INCLUDE_WINDVIEW
#define INCLUDE_WINDVIEW_CLASS
#define INCLUDE_WVUPLOAD_FILE
#define INCLUDE_WVUPLOAD_TSFSSOCK
#define INCLUDE_XBD
#define INCLUDE_XBD_RAMDRV
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_SCSI
#undef INCLUDE_POWER_MGMT_CPU_BSP_SUPPORT
#undef INCLUDE_LPT
#undef INCLUDE_FD
#undef INCLUDE_IDE
#undef INCLUDE_ATA
#undef INCLUDE_AUX_CLK
#undef INCLUDE_SIO_POLL
#undef INCLUDE_PC_CONSOLE
#undef INCLUDE_LOCK_TEXT_SECTION
#undef INCLUDE_PAGE_SIZE_OPTIMIZATION
#undef INCLUDE_CPU_SLEEP_MODE_OFF
#undef INCLUDE_CPU_SLEEP_MODE_SHORT
#undef INCLUDE_CPU_SLEEP_MODE_LONG
#undef INCLUDE_AIM_MMU_MEM_POOL_CONFIG
#undef INCLUDE_AIM_MMU_CONFIG
#undef INCLUDE_AIM_MMU_PT_PROTECTION
#undef INCLUDE_MMU_OPTIMIZE
#undef INCLUDE_TYCODRV_5_2
#undef INCLUDE_SW_FP
#undef INCLUDE_CNS
#undef INCLUDE_HRFS
#undef INCLUDE_HRFS_READONLY
#undef INCLUDE_CDROMFS
#undef INCLUDE_XBD_TRANS
#undef INCLUDE_DOSFS
#undef INCLUDE_HRFS_ACCESS_TIMESTAMP
#undef INCLUDE_XBD_BLK_DEV
#undef INCLUDE_XBD_PART_LIB
#undef INCLUDE_HRFS_FORMAT
#undef INCLUDE_HRFS_CHKDSK
#undef INCLUDE_JOB_QUEUE_UTIL
#undef INCLUDE_ARP_API
#undef INCLUDE_IPWRAP_ARP
#undef INCLUDE_NET_BOOT_IPV6_CFG
#undef INCLUDE_END_POLLED_STATS
#undef INCLUDE_ETHERNET
#undef INCLUDE_FTP6
#undef INCLUDE_GETADDRINFO
#undef INCLUDE_GETNAMEINFO
#undef INCLUDE_IPWRAP_GETNAMEINFO
#undef INCLUDE_GETNAMEINFO_SYSCTL
#undef INCLUDE_GETNETBYNAME
#undef INCLUDE_GETSERVBYNAME
#undef INCLUDE_GETSERVBYPORT
#undef INCLUDE_IPWRAP_GETSERVBYNAME
#undef INCLUDE_IPWRAP_GETSERVBYPORT
#undef INCLUDE_GTF
#undef INCLUDE_GTF_TIMER_START
#undef INCLUDE_NET_HOST_SHOW
#undef INCLUDE_IFCONFIG
#undef INCLUDE_INETLIB
#undef INCLUDE_NET_INIT
#undef INCLUDE_MUX_IF_FUNC_DBASE
#undef INCLUDE_NETBUFADVLIB
#undef INCLUDE_MBUF_UTIL2
#undef INCLUDE_NETSTAT
#undef INCLUDE_IPWRAP_NETSTAT
#undef INCLUDE_NETSTAT_UN_COMP
#undef INCLUDE_PING
#undef INCLUDE_IPWRAP_PING
#undef INCLUDE_PING6
#undef INCLUDE_IPWRAP_PING6
#undef INCLUDE_NET_POOL
#undef INCLUDE_NET_BOOT_CONFIG
#undef INCLUDE_IPATTACH
#undef INCLUDE_IP6ATTACH
#undef INCLUDE_RLOGIN
#undef INCLUDE_ROUTECMD
#undef INCLUDE_IPWRAP_ROUTECMD
#undef INCLUDE_RPC
#undef INCLUDE_XDR_BOOL_T
#undef INCLUDE_XDR
#undef INCLUDE_SECURITY
#undef INCLUDE_TELNET_CLIENT
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_SSI
#undef INCLUDE_IPDHCPC
#undef INCLUDE_IPDHCPR
#undef INCLUDE_IPDHCPS
#undef INCLUDE_IPDHCPC6
#undef INCLUDE_IPDHCPS6
#undef INCLUDE_IPDHCPS6_CMD
#undef INCLUDE_IPFTPC
#undef INCLUDE_IPFTPS
#undef INCLUDE_IPFTP_CMD
#undef INCLUDE_IPPING_CMD
#undef INCLUDE_IPPING6_CMD
#undef INCLUDE_IPRIP
#undef INCLUDE_RIPNG
#undef INCLUDE_IPRIP_CTRL_CMD
#undef INCLUDE_RIPNG_CTRL_CMD
#undef INCLUDE_IPRADVD_CMD
#undef INCLUDE_IPSNTP_COMMON
#undef INCLUDE_IPSNTPC
#undef INCLUDE_IPSNTPS
#undef INCLUDE_IPSNTP_CMD
#undef INCLUDE_IPTELNETS
#undef INCLUDE_IPTFTP_COMMON
#undef INCLUDE_IPTFTPC
#undef INCLUDE_IPTFTP_CLIENT_CMD
#undef INCLUDE_IPTFTPS
#undef INCLUDE_IPDNSC
#undef INCLUDE_NET_INIT_SKIP
#undef INCLUDE_IPNET_USE_PPP
#undef INCLUDE_IPNET_USE_SOCKDEV
#undef INCLUDE_IPCOM_USE_INET6_ONLY
#undef INCLUDE_IPNET_USE_NAT
#undef INCLUDE_IPNET_USE_NETLINKSOCK
#undef INCLUDE_NFS2_CLIENT
#undef INCLUDE_NFS3_CLIENT
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS2_SERVER
#undef INCLUDE_NFS3_SERVER
#undef INCLUDE_NFS_SERVER_INSTALL
#undef INCLUDE_SNMP_STATIC_INIT
#undef INCLUDE_SNMP_DYNAMIC_INIT
#undef INCLUDE_SM_NET
#undef INCLUDE_DSI_DYNAMIC_INIT
#undef INCLUDE_UN_COMP
#undef INCLUDE_WM_SNMP_INIT
#undef INCLUDE_PROCFS
#undef INCLUDE_CBIO
#undef INCLUDE_DISK_PART
#undef INCLUDE_GNU_INTRINSICS
#undef INCLUDE_NO_INTRINSICS
#undef INCLUDE_CPLUS_IOSTREAMS
#undef INCLUDE_POSIX_ADVISORY_FILE_LOCKING
#undef INCLUDE_ATA_SHOW
#undef INCLUDE_PCI_CFGSHOW
#undef INCLUDE_ISR_SHOW
#undef INCLUDE_POOL_SHOW
#undef INCLUDE_SPY
#undef INCLUDE_SIMPLE_BANNER
#undef INCLUDE_ISR_OBJECTS
#undef INCLUDE_TASK_ROTATE
#undef INCLUDE_TASK_UTIL
#undef INCLUDE_ISR_DEFER
#undef INCLUDE_MEM_ALLOT
#undef INCLUDE_PX_SCHED_DEF_POLICIES
#undef INCLUDE_POSIX_PTHREAD_SCHEDULER
#undef INCLUDE_PX_SCHED_SPORADIC_POLICY
#undef INCLUDE_CUSTOM_SCHEDULER
#undef INCLUDE_VX_NATIVE_SCHEDULER
#undef INCLUDE_RAMDRV
#undef INCLUDE_MEMDRV
#undef INCLUDE_VRFS
#undef INCLUDE_UTF
#undef INCLUDE_STRING_SEARCH
#undef INCLUDE_WVNETD
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_POSIX_TRACE
#undef INCLUDE_POSIX_TRACE_TIMESTAMP
#undef INCLUDE_SLL_CREATE_DELETE
#undef INCLUDE_DLL_CREATE_DELETE
#undef INCLUDE_Q_FIFO_CREATE_DELETE
#undef INCLUDE_Q_PRI_LIST_CREATE_DELETE
#undef INCLUDE_Q_PRI_BMAP_CREATE_DELETE
#undef INCLUDE_Q_PRI_DELTA_CREATE_DELETE
#undef INCLUDE_Q_CREATE_DELETE
#undef INCLUDE_AVL_TREES
#undef INCLUDE_WVTIPC
#undef INCLUDE_DOSFS_MAIN
#undef INCLUDE_DOSFS_CACHE
#undef INCLUDE_DOSFS_SHOW
#undef INCLUDE_SCSI_DOSFS
#undef INCLUDE_TFFS
#undef INCLUDE_TFFS_MOUNT
#undef INCLUDE_CORE_DUMP
#undef INCLUDE_DSI_STATIC_INIT
#undef INCLUDE_WDB_SYS_REG
#undef INCLUDE_WDB_SYS
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_COMM_TYCODRV_5_2
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_NETROM
#undef INCLUDE_WDB_COMM_VTMD
#undef INCLUDE_WDB_COMM_END
#undef INCLUDE_WDB_COMM_TIPC
#undef INCLUDE_WDB_COMM_CUSTOM
#undef INCLUDE_TIPC
#undef INCLUDE_WDB_PRE_KERNEL_INIT
#undef INCLUDE_RTP_APPL_USER
#undef INCLUDE_RTP_POSIX_PSE52
#undef INCLUDE_POSIX_THREAD_CPUTIME
#undef INCLUDE_POSIX_SHM
#undef INCLUDE_POSIX_MAPPED_FILES
#undef INCLUDE_STANDALONE_SYM_TBL
#undef INCLUDE_SHELL_HISTORY_FILE
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_IPWRAP_GETHOSTBYNAME
#undef INCLUDE_IPWRAP_GETHOSTBYADDR
#undef INCLUDE_IPARP_CMD
#undef INCLUDE_IPWRAP_IFNAME
#undef INCLUDE_IPWRAP_GETIFADDRS
#undef INCLUDE_IPWRAP_SNTPCTIMEGET
#undef INCLUDE_CORE_NFS_CLIENT
#undef INCLUDE_NFS_CLIENT_ALL
#undef INCLUDE_CORE_NFS_SERVER
#undef INCLUDE_NFS_SERVER_ALL
#undef INCLUDE_BOOT_APP
#undef INCLUDE_BOOT_ELF
#undef INCLUDE_BOOT_END
#undef INCLUDE_BOOT_EXC_HANDLER
#undef INCLUDE_BOOT_FTP_LOADER
#undef INCLUDE_BOOT_INIT
#undef INCLUDE_BOOT_MEM_CMDS
#undef INCLUDE_BOOT_NETWORK
#undef INCLUDE_BOOT_SHELL
#undef INCLUDE_BOOT_RSH_LOADER
#undef INCLUDE_BOOT_TFTP_LOADER
#undef INCLUDE_RTP_APPL_INIT_STRING
#undef INCLUDE_RTP_APPL_INIT_CMD_SHELL_SCRIPT
#undef INCLUDE_SM_COMMON
#undef INCLUDE_SM_AND_DSHM
#undef INCLUDE_SM_NET_SHOW
#undef INCLUDE_SMEND
#undef INCLUDE_SYSCTL_CLI
#undef INCLUDE_VXTESTV2
#undef INCLUDE_VXTESTV2_WDB
#undef INCLUDE_VXTESTV2_SHELL
#undef INCLUDE_VXTESTV2_SHELLPROC
#undef INCLUDE_VXTESTV2_SCALE
#undef INCLUDE_VXTESTV2_EMBEDDED
#undef INCLUDE_VXTESTV2_AUTORUN
#undef INCLUDE_VXTESTV2_SYSPARAMS
#undef INCLUDE_VXTESTV2_POSIX_FS
#undef INCLUDE_TM_BOOT_APP
#undef INCLUDE_BOOT_TEST_FUNCS
#undef INCLUDE_BOOT_RAM_IMAGE
#undef INCLUDE_TM_CACHELIB
#undef INCLUDE_TM_CACHELIB_MALLOC
#undef INCLUDE_TM_MODEL
#undef INCLUDE_TM_SYSCLOCK
#undef INCLUDE_TM_AUXCLOCK
#undef INCLUDE_TM_NVRAM
#undef INCLUDE_TM_TIMESTAMP
#undef INCLUDE_TM_INTARCHLIB
#undef INCLUDE_TM_PINGLIB
#undef INCLUDE_TM_CPCLIB
#undef INCLUDE_TM_CPUSET
#undef INCLUDE_TM_ERRNOLIB_SMP
#undef INCLUDE_TM_KERNELLIBSMP
#undef INCLUDE_TM_SPINLOCKLIB
#undef INCLUDE_TM_TASKLIBSMP
#undef INCLUDE_TM_VXATOMICLIB
#undef INCLUDE_TM_VXCPULIB
#undef INCLUDE_TM_VXBUS
#undef INCLUDE_TM_VXB_PCI_ACCESS
#undef INCLUDE_PCI_BUS
#undef INCLUDE_TM_VXB_VIRT_ACCESS
#undef INCLUDE_TM_VXB_PARAM_SYS
#undef INCLUDE_PARAM_SYS
#undef INCLUDE_TM_VXB_DMA_SYS
#undef INCLUDE_DMA_SYS
#undef INCLUDE_TM_VXB_DMA_LIB
#undef INCLUDE_TM_VXB_TIMER_LIB
#undef INCLUDE_TM_VXB_SIO
#undef INCLUDE_SIO_UTILS
#undef INCLUDE_TM_VXB_TIMER_DRV
#undef INCLUDE_SM_OBJ
#undef INCLUDE_WDB_PROXY
#undef INCLUDE_WDB_PROXY_UDP
#undef INCLUDE_WDB_PROXY_TIPC
#undef INCLUDE_SAL_CLIENT
#undef INCLUDE_SAL_SERVER
#undef INCLUDE_SNS_SHOW
#undef INCLUDE_SAL_COMMON
#undef INCLUDE_SNS
#undef INCLUDE_SNS_RTP
#undef INCLUDE_SNS_MP
#undef INCLUDE_SNS_MP_RTP
#undef INCLUDE_SNS_COMMON
#undef INCLUDE_SNS_RTP_HOOK
#undef INCLUDE_UN
#undef INCLUDE_DSI_SOCKET
#undef INCLUDE_DSI_POOL
#undef INCLUDE_UN_SHOW
#undef INCLUDE_UN_COMP_SHOW
#undef INCLUDE_CORE_DUMP_SHOW
#undef INCLUDE_CORE_DUMP_MEM_FILTER
#undef INCLUDE_CORE_DUMP_MEM
#undef INCLUDE_CORE_DUMP_MEM_POOL
#undef INCLUDE_CORE_DUMP_COMPRESS
#undef INCLUDE_CORE_DUMP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_UTIL
#undef INCLUDE_CORE_DUMP_RAW_DEV
#undef INCLUDE_CORE_DUMP_STREAM_DEV
#undef INCLUDE_MEM_EDR
#undef INCLUDE_MEM_EDR2
#undef INCLUDE_MEM_EDR_RTC
#undef INCLUDE_MEM_EDR_SHOW
#undef INCLUDE_MEM_EDR_RTP_SHOW
#undef INCLUDE_MAPPED_FILES_SHOW
#undef INCLUDE_MAPPED_FILES_SHOW_SHELL_CMD
#undef INCLUDE_MEM_EDR_SHELL_CMD
#undef INCLUDE_MEM_EDR_RTP_SHELL_CMD
#undef INCLUDE_HISTORY_FILE_SHELL_CMD
#undef INCLUDE_TFFS_SHOW
#undef INCLUDE_MTD_AMD
#undef INCLUDE_MTD_I28F008
#undef INCLUDE_MTD_I28F008BAJA
#undef INCLUDE_MTD_I28F016
#undef INCLUDE_MTD_WAMDMTD
#undef INCLUDE_MTD_CFIAMD
#undef INCLUDE_MTD_CFISCS
#undef INCLUDE_TL_FTL
#undef INCLUDE_TL_SSFDC
#undef INCLUDE_DOSFS_FAT
#undef INCLUDE_DOSFS_FMT
#undef INCLUDE_DOSFS_CHKDSK
#undef INCLUDE_TAR
#undef INCLUDE_DOSFS_DIR_VFAT
#undef INCLUDE_DOSFS_DIR_FIXED
#undef INCLUDE_DOWNLOADABLE_DRIVERS
#undef INCLUDE_NON_VOLATILE_RAM
#undef INCLUDE_TIMER_STUB
#undef INCLUDE_USB_INIT
#undef INCLUDE_EHCI_INIT
#undef INCLUDE_OHCI_INIT
#undef INCLUDE_UHCI_INIT
#undef VXBUS_TABLE_CONFIG
#undef INCLUDE_PCI_BUS_AUTOCONF
#undef INCLUDE_PCI_OLD_CONFIG_ROUTINES
#undef INCLUDE_PCI_BUS_SHOW
#undef INCLUDE_VXBUS_SM_SUPPORT
#undef INCLUDE_XBD_CBIO_DEV
#undef INCLUDE_RAPIDIO_BUS
#undef RAPIDIO_BUS_AUTOCONFIG
#undef RAPIDIO_BUS_STATIC_PROBE
#undef RAPIDIO_BUS_STATIC_TABLE
#undef INCLUDE_VXB_LEGACY_INTERRUPTS
#undef INCLUDE_BOOT_DELAYED_INIT
#undef INCLUDE_BOOT_MMU_BASIC
#undef INCLUDE_BOOT_EDR_SUPPORT
#undef INCLUDE_BOOT_NET_DEVICES
#undef INCLUDE_BOOT_VXBUS
#undef INCLUDE_BOOT_ETH_MAC_HANDLER
#undef INCLUDE_BOOT_ETH_ADR_SET
#undef INCLUDE_BOOT_DHCPC
#undef INCLUDE_BOOT_FILESYSTEMS
#undef INCLUDE_BOOT_FS_DEVICES
#undef INCLUDE_BOOT_FD_LOADER
#undef INCLUDE_BOOT_USB_FS_LOADER
#undef INCLUDE_USB_MS_BULKONLY
#undef INCLUDE_BOOT_SCSI_LOADER
#undef INCLUDE_BOOT_ATA_LOADER
#undef INCLUDE_BOOT_PCMCIA_LOADER
#undef INCLUDE_BOOT_TSFS_LOADER
#undef INCLUDE_BOOT_TFFS_LOADER
#undef INCLUDE_DSHM
#undef INCLUDE_DSHM_MUX
#undef INCLUDE_DSHM_ADAPT
#undef INCLUDE_DSHM_DEBUG
#undef INCLUDE_DSHM_SVC_MNG
#undef INCLUDE_DSHM_MSG_SM
#undef INCLUDE_DSHM_NOWRING
#undef INCLUDE_DSHM_BUS
#undef INCLUDE_DSHM_BUS_PLB
#undef INCLUDE_DSHM_VXPLB
#undef INCLUDE_DSHM_MEM
#undef INCLUDE_DSHM_RW_LOCK
#undef INCLUDE_DSHM_OWRING
#undef INCLUDE_DSHM_SPINLOCK
#undef INCLUDE_DSHM_POW2
#undef INCLUDE_TIPC_SHOW
#undef INCLUDE_CONFIG_TIPC_SOCKET_API
#undef INCLUDE_TIPC_MEMPOOL
#undef INCLUDE_TIPC_DEFINES
#undef INCLUDE_TIPC_NODEBUG
#undef INCLUDE_TIPC_NOSYS_MSGS
#undef INCLUDE_TIPC_NOCFG_SERVICE
#undef INCLUDE_TIPC_NOSOCKET
#undef INCLUDE_USE_LIBTIPC
#undef INCLUDE_TIPC_CONFIG_STR
#undef INCLUDE_TIPC_CONFIG_HOOK_BOOT
#undef INCLUDE_TIPC_CONFIG_HOOK_USER
#undef INCLUDE_TIPC_MEDIA_ETH
#undef INCLUDE_TIPC_IP
#undef INCLUDE_TIPC_ONLY
#undef INCLUDE_TIPC_TS
#undef INCLUDE_TIPC_IS
#undef INCLUDE_AMP
#undef INCLUDE_AMP_SM_END_AUTO
#undef INCLUDE_DSHM_SVC_TIPC_PRIM
#undef INCLUDE_VXBUS_END_QCTRL
#undef DRV_TIMER_MIPSR4K
#undef DRV_TIMER_SB1
#undef DRV_TIMER_CN3XXX
#undef DRV_TIMER_OPENPIC
#undef INCLUDE_AN983_VXB_END
#undef INCLUDE_GENERICPHY
#undef INCLUDE_VXB_CPM
#undef INCLUDE_TC3C905_VXB_END
#undef INCLUDE_EMAC_VXB_NET
#undef INCLUDE_VXB_IBM_MAL
#undef INCLUDE_NE2000_VXB_END
#undef INCLUDE_MOT_ETSEC_HEND
#undef INCLUDE_FCC_VXB_END
#undef INCLUDE_MII_BUS
#undef INCLUDE_MDIO
#undef INCLUDE_BCM52XXPHY
#undef INCLUDE_MOT_FEC_HEND
#undef INCLUDE_FEC_VXB_END
#undef INCLUDE_FEI8255X_VXB_END
#undef INCLUDE_GT64120A_MF
#undef INCLUDE_GT64120A_PCI
#undef INCLUDE_GT64120A_DMA
#undef INCLUDE_GT64120A_TIMER
#undef INCLUDE_GT64120A_INTCTLR
#undef INCLUDE_GT64120A_SDRAM
#undef INCLUDE_GT64120A_I2O
#undef INCLUDE_GEI_HEND
#undef INCLUDE_GEI825XX_VXB_END
#undef INCLUDE_HEND_PARAM_SYS
#undef INCLUDE_HEND_NPT
#undef DRV_I8259VXBPIC
#undef DRV_TIMER_IXP400
#undef DRV_PCIBUS_IXP4XX
#undef INCLUDE_AM79C97X_VXB_END
#undef DRV_PCIBUS_M83XX
#undef DRV_RESOURCE_M85XXCCSR
#undef INCLUDE_M85XX_CPU
#undef DRV_PCIBUS_M85XX
#undef INCLUDE_M85XX_RAPIDIO
#undef INCLUDE_M85XX_RIO_SM_CFG
#undef INCLUDE_GENERICTBIPHY
#undef INCLUDE_BCM54XXPHY
#undef INCLUDE_DM9161PHY
#undef INCLUDE_GEITBIPHY
#undef INCLUDE_LXT972PHY
#undef INCLUDE_MV88E1X11PHY
#undef INCLUDE_MV88E1113PHY
#undef INCLUDE_RTL8201PHY
#undef INCLUDE_VSC82XXPHY
#undef INCLUDE_TSEC_MDIO
#undef INCLUDE_NS83902_VXB_END
#undef INCLUDE_NS8381X_VXB_END
#undef DRV_KBD_I8042
#undef DRV_VGA_M6845
#undef DRV_TIMER_DEC_PPC
#undef INCLUDE_QE_FCC_HEND
#undef INCLUDE_QUICC_ENGINE_UTILS
#undef INCLUDE_RTL8169_VXB_END
#undef INCLUDE_RTL8139_VXB_END
#undef INCLUDE_SBE_VXB_END
#undef INCLUDE_SCC_VXB_END
#undef INCLUDE_MOT_TSEC_HEND
#undef INCLUDE_TSEC_VXB_END
#undef DRV_SIO_NS16550
#undef DRV_SIO_COLDFIRE
#undef DRV_SIO_IXP400
#undef DRV_SIO_SB1
#undef DRV_SIO_PRIMECELL
#undef DRV_SIO_OCTEON
#undef INCLUDE_USB
#undef INCLUDE_OHCI
#undef INCLUDE_UHCI
#undef INCLUDE_EHCI
#undef INCLUDE_PDIUSBD12
#undef INCLUDE_PHILIPS1582
#undef INCLUDE_NET2280
#undef INCLUDE_USB_TARG
#undef INCLUDE_KBD_EMULATOR
#undef INCLUDE_PRN_EMULATOR
#undef INCLUDE_D12_EMULATOR
#undef INCLUDE_MS_EMULATOR
#undef INCLUDE_KBD_EMULATOR_INIT
#undef INCLUDE_PRN_EMULATOR_INIT
#undef INCLUDE_MS_EMULATOR_INIT
#undef INCLUDE_USB_MOUSE
#undef INCLUDE_USB_KEYBOARD
#undef INCLUDE_USB_PRINTER
#undef INCLUDE_USB_SPEAKER
#undef INCLUDE_USB_PEGASUS_END
#undef INCLUDE_USB_MS_CBI
#undef INCLUDE_USB_AUDIO_DEMO
#undef INCLUDE_USB_HEADSET_DEMO
#undef INCLUDE_UHCI_BUS
#undef INCLUDE_OHCI_BUS
#undef INCLUDE_EHCI_BUS
#undef INCLUDE_USB_MOUSE_INIT
#undef INCLUDE_USB_KEYBOARD_INIT
#undef INCLUDE_USB_PRINTER_INIT
#undef INCLUDE_USB_SPEAKER_INIT
#undef INCLUDE_USB_MS_BULKONLY_INIT
#undef INCLUDE_USB_MS_CBI_INIT
#undef INCLUDE_USB_PEGASUS_END_INIT
#undef INCLUDE_USBTOOL
#undef DRV_INTCTLR_EPIC
#undef INCLUDE_ETSEC_VXB_END
#undef DRV_NVRAM_FILE
#undef DRV_TIMER_I8253
#undef DRV_INTCTLR_I8259
#undef INCLUDE_IPIIX4_MF
#undef INCLUDE_INTCTLR_DYNAMIC_LIB
#undef INCLUDE_DRV_STORAGE_INTEL_ICH
#undef INCLUDE_DRV_STORAGE_INTEL_ICH_SHOW
#undef DRV_TIMER_IA_TIMESTAMP
#undef DRV_INTCTLR_IOAPIC
#undef DRV_INTCTLR_LOAPIC
#undef DRV_TIMER_LOAPIC
#undef DRV_TIMER_M85XX
#undef DRV_TIMER_MC146818
#undef DRV_INTCTLR_MIPS
#undef DRV_INTCTLR_MIPS_SBE
#undef DRV_INTCTLR_MIPS_CAV
#undef DRV_INTCTLR_MPAPIC
#undef INCLUDE_MSC01_PCI
#undef INCLUDE_PPC440GX_PCI
#undef DRV_TIMER_QUICC_PPC
#undef DRV_INTCTLR_QE
#undef DRV_INTCTLR_QUICC
#undef DRV_STORAGE_SI31XX
#undef DRV_SUPERIO_SMCFDC37X
#undef INCLUDE_SMSCLAN9118_VXB_END
#undef DRV_INTCTLR_VXSIM
#undef INCLUDE_MVYUKON_VXB_END
#undef INCLUDE_MVYUKONII_VXB_END
#undef INCLUDE_HOST_SIO
#undef INCLUDE_DSHM_BUS_CTLR_SIM
#undef INCLUDE_DSHM_VXSIM
#undef INCLUDE_DSHM_SVC_TIPC
#undef INCLUDE_TIPC_MEDIA_SM
#undef INCLUDE_IPCOM_USE_AUTH
#undef INCLUDE_IPCOM_AUTH_1
#undef INCLUDE_IPCOM_AUTH_2
#undef INCLUDE_IPCOM_AUTH_3
#undef INCLUDE_IPCOM_AUTH_4
#undef INCLUDE_IPCOM_AUTH_5
#undef INCLUDE_IPCOM_AUTH_6
#undef INCLUDE_USE_IPCOM_SHELL
#undef INCLUDE_USE_NATIVE_SHELL
#undef INCLUDE_IPCOM_USE_VXSHELL_CMD
#undef INCLUDE_IPCOM_USE_RAM_DISK
#undef INCLUDE_IPCOM_FS_IPCOM
#undef INCLUDE_IPCOM_FS_NATIVE
#undef INCLUDE_IPNET_IFCONFIG_2
#undef INCLUDE_IPNET_IFCONFIG_3
#undef INCLUDE_IPNET_IFCONFIG_4
#undef INCLUDE_IPNET_PACKET_POOL_1
#undef INCLUDE_IPNET_PACKET_POOL_2
#undef INCLUDE_IPNET_PACKET_POOL_7
#undef INCLUDE_IPNET_PACKET_POOL_8
#undef INCLUDE_IPNET_PACKET_POOL_9
#undef INCLUDE_IPNET_PACKET_POOL_10
#undef INCLUDE_IPAIP_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_USE_WLAN
#undef INCLUDE_IPPPP
#undef INCLUDE_IPPPP_INTERFACE_CONFIG
#undef INCLUDE_IPPPP_USERS_CONFIG
#undef INCLUDE_IPPPPOE
#undef INCLUDE_IPPPP_CMD
#undef INCLUDE_IPNET6_AUTOCONF_PRIVACY_EXT
#undef INCLUDE_IPNET6_PRIVACY_GLOBAL_CONFIGS
#undef INCLUDE_IPNET6_PRIVACY_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_CLASSIFIER
#undef INCLUDE_IPNET_DIFFSERV
#undef INCLUDE_IPNET_DS_SM
#undef INCLUDE_IPNET_DS_SRTCM
#undef INCLUDE_IPQOS_CMD
#undef INCLUDE_IPQUEUE_CONFIG_CMD
#undef INCLUDE_IPNET_IFQUEUE_FIFO_DEFAULT
#undef INCLUDE_IPRIP_IFCONFIG_1
#undef INCLUDE_IPRIP_IFCONFIG_2
#undef INCLUDE_IPRIP_IFCONFIG_3
#undef INCLUDE_IPRIP_IFCONFIG_4
#undef INCLUDE_IPRIP_STATIC_ROUTE_1
#undef INCLUDE_IPRIP_STATIC_ROUTE_2
#undef INCLUDE_IPRIP_STATIC_ROUTE_3
#undef INCLUDE_IPCOM_SYSLOGD_CMD
#undef INCLUDE_IPCOM_SYSLOGD_USE_LOG_FILE
#undef INCLUDE_IPCOM_SYSVAR_CMD
#undef INCLUDE_IPECHO_CLIENT_CMD
#undef INCLUDE_IPECHO_SERVER_CMD
#undef INCLUDE_IPD_CMD
#undef INCLUDE_IPNET_CTRL_CMD
#undef INCLUDE_IPMEM_DEBUG_CMD
#undef INCLUDE_IPNAT_CMD
#undef INCLUDE_IPNDP_CMD
#undef INCLUDE_IPNETSTAT_CMD
#undef INCLUDE_IPNSLOOKUP_CMD
#undef INCLUDE_IPROUTE_CMD
#undef INCLUDE_IPNET_SCALETEST_CMD
#undef INCLUDE_IPSOCKPERF_CMD
#undef INCLUDE_IPSOCKTEST_CMD
#undef INCLUDE_IPTRACE_ROUTE_CMD
#undef INCLUDE_IPTCP_TEST_CMD
#undef INCLUDE_IPCOM_USE_TIME_CMD
#undef INCLUDE_IPVERSION_CMD
#undef INCLUDE_IPCOM_USE_MIB2_CMD


/*** PARAMETERS ***/

#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE BOOT_LINE_ADRS
#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS 0x60000000
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE 0x02000000
#undef  LOCAL_MEM_AUTOSIZE
#undef  USER_RESERVED_MEM
#define USER_RESERVED_MEM 0
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE 0x100
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS 0
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x800
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS (BOOT_LINE_ADRS + BOOT_LINE_SIZE)
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE ROUND_UP (sizeof (BOOT_PARAMS), 0x100)
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+BOOT_LINE_OFFSET))
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x700
#undef  RESERVED
#define RESERVED 0
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS (end)
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS (0x0)
#undef  STACK_SAVE
#define STACK_SAVE 0x40
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0xffffffff
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x60010000
#undef  ROM_BASE_ADRS
#define ROM_BASE_ADRS 0x0
#undef  ROM_TEXT_ADRS
#define ROM_TEXT_ADRS (ROM_BASE_ADRS) 
#undef  ROM_SIZE
#define ROM_SIZE 0x0
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE CACHE_COPYBACK
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  SW_MMU_ENABLE
#define SW_MMU_ENABLE FALSE
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE 0x2000
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 50
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 2
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 100
#undef  NUM_TTY
#define NUM_TTY 1
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 9600
#undef  APPL_LOG_FD_CFG
#define APPL_LOG_FD_CFG STD_OUT
#undef  APPL_LOG_LEVEL_CFG
#define APPL_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  APPL_KERN_LOG_FD_CFG
#define APPL_KERN_LOG_FD_CFG KERN_LOG_FD
#undef  APPL_KERN_LOG_LEVEL_CFG
#define APPL_KERN_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  NET_JOB_NUM_CFG
#define NET_JOB_NUM_CFG 85
#undef  NET_TASK_PRIORITY
#define NET_TASK_PRIORITY 50
#undef  NET_TASK_OPTIONS
#define NET_TASK_OPTIONS VX_SUPERVISOR_MODE | VX_UNBREAKABLE
#undef  NET_TASK_STACKSIZE
#define NET_TASK_STACKSIZE 10000
#undef  NUM_NET_DAEMONS
#define NUM_NET_DAEMONS 1
#undef  NET_DAEMONS_CPU_AFFINITY
#define NET_DAEMONS_CPU_AFFINITY FALSE
#undef  FTP_TRANSIENT_MAX_RETRY_COUNT
#define FTP_TRANSIENT_MAX_RETRY_COUNT 100
#undef  FTP_TRANSIENT_RETRY_INTERVAL
#define FTP_TRANSIENT_RETRY_INTERVAL 0
#undef  FTP_TRANSIENT_FATAL
#define FTP_TRANSIENT_FATAL ftpTransientFatal
#undef  FTP_DEBUG_OPTIONS
#define FTP_DEBUG_OPTIONS 0
#undef  FTP_TIMEOUT
#define FTP_TIMEOUT 0
#undef  NETBUF_LEADING_CLSPACE_DRV
#define NETBUF_LEADING_CLSPACE_DRV 64
#undef  RSH_STDERR_SETUP_TIMEOUT
#define RSH_STDERR_SETUP_TIMEOUT -1
#undef  REM_NUM_CONN_RETRIALS
#define REM_NUM_CONN_RETRIALS 3
#undef  CLEAR_BSS
#define CLEAR_BSS
#undef  MAX_LIO_CALLS
#define MAX_LIO_CALLS 0
#undef  MAX_AIO_SYS_TASKS
#define MAX_AIO_SYS_TASKS 0
#undef  AIO_TASK_PRIORITY
#define AIO_TASK_PRIORITY 0
#undef  AIO_TASK_STACK_SIZE
#define AIO_TASK_STACK_SIZE 0
#undef  MQ_HASH_SIZE
#define MQ_HASH_SIZE 0
#undef  NUM_SIGNAL_QUEUES
#define NUM_SIGNAL_QUEUES 16
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 20000
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 50000
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x1
#undef  TASK_USER_EXC_STACK_SIZE
#define TASK_USER_EXC_STACK_SIZE (8192*3)
#undef  TASK_USER_EXC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_USER_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  WIND_JOBS_MAX
#define WIND_JOBS_MAX 64
#undef  VX_GLOBAL_NO_STACK_FILL
#define VX_GLOBAL_NO_STACK_FILL FALSE
#undef  MAX_REBOOT_HOOKS
#define MAX_REBOOT_HOOKS 8
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  MAX_ISR_JOBS
#define MAX_ISR_JOBS 16
#undef  JOB_TASK_STACK_SIZE
#define JOB_TASK_STACK_SIZE 8000
#undef  FUNCPTR_OBJ_MEMALLOC_RTN
#define FUNCPTR_OBJ_MEMALLOC_RTN memPartAlloc
#undef  FUNCPTR_OBJ_MEMFREE_RTN
#define FUNCPTR_OBJ_MEMFREE_RTN memPartFree
#undef  OBJ_MEM_POOL_ID
#define OBJ_MEM_POOL_ID memSysPartId
#undef  OBJ_LIBRARY_OPTIONS
#define OBJ_LIBRARY_OPTIONS 0
#undef  SEM_RW_MAX_CONCURRENT_READERS
#define SEM_RW_MAX_CONCURRENT_READERS 32
#undef  MEM_PART_DEFAULT_OPTIONS
#define MEM_PART_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_SUSPEND_FLAG | MEM_BLOCK_CHECK)
#undef  POSIX_SIGNAL_MODE
#define POSIX_SIGNAL_MODE FALSE
#undef  EDR_PM_ARENA
#define EDR_PM_ARENA pmDefaultArena
#undef  PM_RESERVED_MEM
#define PM_RESERVED_MEM 0x100000
#undef  EDR_ERRLOG_SIZE
#define EDR_ERRLOG_SIZE 0x80000
#undef  EDR_RECORD_SIZE
#define EDR_RECORD_SIZE 4096
#undef  VX_TRAD_SCHED_CONSTANT_RDY_Q
#define VX_TRAD_SCHED_CONSTANT_RDY_Q TRUE
#undef  IOS_POSIX_PSE52_MODE
#define IOS_POSIX_PSE52_MODE FALSE
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  NUM_FILES
#define NUM_FILES 50
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  INIT_NBIO_MSGS
#define INIT_NBIO_MSGS 32
#undef  TYLIB_XOFF_PCNT
#define TYLIB_XOFF_PCNT 85
#undef  TYLIB_XON_PCNT
#define TYLIB_XON_PCNT 50
#undef  TYLIB_WRT_THRESHLD
#define TYLIB_WRT_THRESHLD 20
#undef  NUM_RAWFS_FILES
#define NUM_RAWFS_FILES 5
#undef  ERF_MAX_USR_CATEGORIES
#define ERF_MAX_USR_CATEGORIES 16
#undef  ERF_MAX_USR_TYPES
#define ERF_MAX_USR_TYPES 16
#undef  DEVICE_MANAGER_MAX_NUM_DEVICES
#define DEVICE_MANAGER_MAX_NUM_DEVICES 255
#undef  WV_DEFAULT_BUF_MIN
#define WV_DEFAULT_BUF_MIN 4
#undef  WV_DEFAULT_BUF_MAX
#define WV_DEFAULT_BUF_MAX 10
#undef  WV_DEFAULT_BUF_SIZE
#define WV_DEFAULT_BUF_SIZE 0x8000
#undef  WV_DEFAULT_BUF_THRESH
#define WV_DEFAULT_BUF_THRESH 0x4000
#undef  WV_DEFAULT_BUF_OPTIONS
#define WV_DEFAULT_BUF_OPTIONS 0x0
#undef  WV_MAX_LOGS
#define WV_MAX_LOGS 5
#undef  WV_UPLOAD_STACKSIZE
#define WV_UPLOAD_STACKSIZE 5000
#undef  WV_UPLOAD_PRIORITY
#define WV_UPLOAD_PRIORITY 150
#undef  WV_RBUFF_MGR_PRIORITY
#define WV_RBUFF_MGR_PRIORITY 100
#undef  INTERRUPT_STACK_OVERFLOW_SIZE
#define INTERRUPT_STACK_OVERFLOW_SIZE 4096
#undef  INTERRUPT_STACK_UNDERFLOW_SIZE
#define INTERRUPT_STACK_UNDERFLOW_SIZE 4096
#undef  WDB_COMM_PORT
#define WDB_COMM_PORT 0x4321
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_POOL_SIZE
#define WDB_POOL_SIZE ((unsigned int) (sysMemTop() - FREE_RAM_ADRS)/16)
#undef  WDB_BP_MAX
#define WDB_BP_MAX 25
#undef  WDB_GOPHER_TAPE_LEN
#define WDB_GOPHER_TAPE_LEN 1400
#undef  WDB_GOPHER_TAPE_NB
#define WDB_GOPHER_TAPE_NB 10
#undef  WDB_REGS_SIZE
#define WDB_REGS_SIZE 512
#undef  WDB_RTP_PRIORITY
#define WDB_RTP_PRIORITY 200
#undef  WDB_MTU
#define WDB_MTU 1500
#undef  WDB_SPAWN_STACK_SIZE
#define WDB_SPAWN_STACK_SIZE 0x5000
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  STORE_ABS_SYMBOLS
#define STORE_ABS_SYMBOLS FALSE
#undef  STAT_TBL_HASH_SIZE_LOG2
#define STAT_TBL_HASH_SIZE_LOG2 6
#undef  SYM_TBL_HASH_SIZE_LOG2
#define SYM_TBL_HASH_SIZE_LOG2 8
#undef  RTP_KERNEL_STACK_SIZE
#define RTP_KERNEL_STACK_SIZE 0x1000
#undef  KERNEL_HEAP_SIZE
#define KERNEL_HEAP_SIZE ((unsigned int)(sysMemTop() - FREE_RAM_ADRS) / 3 * 2)
#undef  RTP_HOOK_TBL_SIZE
#define RTP_HOOK_TBL_SIZE 8
#undef  SYSCALL_HOOK_TBL_SIZE
#define SYSCALL_HOOK_TBL_SIZE 8
#undef  RTP_SIGNAL_QUEUE_SIZE
#define RTP_SIGNAL_QUEUE_SIZE 32
#undef  RTP_HEAP_INIT_SIZE
#define RTP_HEAP_INIT_SIZE 0x10000
#undef  RTP_HEAP_DEFAULT_OPTIONS
#define RTP_HEAP_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG      |                          MEM_ALLOC_ERROR_EDR_WARN_FLAG |                          MEM_BLOCK_ERROR_LOG_FLAG      |                          MEM_BLOCK_ERROR_EDR_FATAL_FLAG |                          MEM_BLOCK_CHECK)
#undef  RTP_FD_NUM_MAX
#define RTP_FD_NUM_MAX 20
#undef  SD_HOOK_TBL_SIZE
#define SD_HOOK_TBL_SIZE 8
#undef  SHELL_TASK_NAME_BASE
#define SHELL_TASK_NAME_BASE "tShell"
#undef  SHELL_TASK_PRIORITY
#define SHELL_TASK_PRIORITY 1
#undef  SHELL_TASK_OPTIONS
#define SHELL_TASK_OPTIONS (VX_FP_TASK | VX_UNBREAKABLE | COPROCS_ALL | VX_PRIVATE_ENV)
#undef  SHELL_STACK_SIZE
#define SHELL_STACK_SIZE 0x10000
#undef  SHELL_SECURE
#define SHELL_SECURE FALSE
#undef  SHELL_START_AT_BOOT
#define SHELL_START_AT_BOOT TRUE
#undef  SHELL_COMPATIBLE
#define SHELL_COMPATIBLE FALSE
#undef  SHELL_DEFAULT_CONFIG
#define SHELL_DEFAULT_CONFIG "LINE_EDIT_MODE=,LINE_LENGTH=256,STRING_FREE=manual,INTERPRETER=,VXE_PATH=.;/romfs"
#undef  SHELL_FIRST_CONFIG
#define SHELL_FIRST_CONFIG NULL
#undef  SHELL_REMOTE_CONFIG
#define SHELL_REMOTE_CONFIG NULL
#undef  RAM_DISK_BLK_SIZE
#define RAM_DISK_BLK_SIZE 512
#undef  RAM_DISK_SIZE
#define RAM_DISK_SIZE 0x10000
#undef  RAM_DISK_DEV_NAME
#define RAM_DISK_DEV_NAME "/ram0"
#undef  HWMEM_POOL_SIZE
#define HWMEM_POOL_SIZE 50000
#undef  SYSCLK_TIMER_NAME
#define SYSCLK_TIMER_NAME NULL
#undef  SYSCLK_TIMER_UNIT
#define SYSCLK_TIMER_UNIT 0
#undef  SYSCLK_TIMER_NUM
#define SYSCLK_TIMER_NUM 0
#undef  AUXCLK_TIMER_NAME
#define AUXCLK_TIMER_NAME NULL
#undef  AUXCLK_TIMER_UNIT
#define AUXCLK_TIMER_UNIT 0
#undef  AUXCLK_TIMER_NUM
#define AUXCLK_TIMER_NUM 0
#undef  TIMESTAMP_TIMER_NAME
#define TIMESTAMP_TIMER_NAME NULL
#undef  TIMESTAMP_TIMER_UNIT
#define TIMESTAMP_TIMER_UNIT 0
#undef  TIMESTAMP_TIMER_NUM
#define TIMESTAMP_TIMER_NUM 0
#undef  CPU_PWR_TASK_P_STATE
#define CPU_PWR_TASK_P_STATE (cpuPwrP0State)
#undef  CPU_PWR_ISR_P_STATE
#define CPU_PWR_ISR_P_STATE (0)
#undef  CPU_PWR_HIGH_THRESHOLD
#define CPU_PWR_HIGH_THRESHOLD (100)
#undef  CPU_PWR_LOW_THRESHOLD
#define CPU_PWR_LOW_THRESHOLD (0)
#undef  CPU_PWR_UTIL_PERIOD1
#define CPU_PWR_UTIL_PERIOD1 (300)
#undef  CPU_PWR_UTIL_PERIOD2
#define CPU_PWR_UTIL_PERIOD2 (1000)
#undef  PASSFS_CACHE
#define PASSFS_CACHE TRUE
#undef  IFCONFIG_1
#define IFCONFIG_1 "ifname","devname driver","inet driver", "gateway driver",                 "inet6 3ffe:1:2:3::4/64"
#undef  IFCONFIG_LOOPBACK
#define IFCONFIG_LOOPBACK "ifname lo0","inet 127.0.0.1/32","inet6 ::1/128","inet6 FF01::1/16"
#undef  NUM_POOL_3
#define NUM_POOL_3 25
#undef  SIZE_POOL_3
#define SIZE_POOL_3 256
#undef  MIN_PRIO_POOL_3
#define MIN_PRIO_POOL_3 0
#undef  NUM_POOL_4
#define NUM_POOL_4 50
#undef  SIZE_POOL_4
#define SIZE_POOL_4 512
#undef  MIN_PRIO_POOL_4
#define MIN_PRIO_POOL_4 0
#undef  NUM_POOL_5
#define NUM_POOL_5 90
#undef  SIZE_POOL_5
#define SIZE_POOL_5 1500
#undef  MIN_PRIO_POOL_5
#define MIN_PRIO_POOL_5 0
#undef  NUM_POOL_6
#define NUM_POOL_6 5
#undef  SIZE_POOL_6
#define SIZE_POOL_6 10000
#undef  MIN_PRIO_POOL_6
#define MIN_PRIO_POOL_6 0
#undef  NUM_POOL_11
#define NUM_POOL_11 1
#undef  SIZE_POOL_11
#define SIZE_POOL_11 65535
#undef  MIN_PRIO_POOL_11
#define MIN_PRIO_POOL_11 0
#undef  INET_IPAIP_IFNAME_LIST
#define INET_IPAIP_IFNAME_LIST ""
#undef  INET_IPAIP_PROBE_WAIT
#define INET_IPAIP_PROBE_WAIT "1"
#undef  INET_IPAIP_PROBE_NUM
#define INET_IPAIP_PROBE_NUM "3"
#undef  INET_IPAIP_PROBE_MIN
#define INET_IPAIP_PROBE_MIN "1"
#undef  INET_IPAIP_PROBE_MAX
#define INET_IPAIP_PROBE_MAX "3"
#undef  INET_IPAIP_ANNOUNCE_WAIT
#define INET_IPAIP_ANNOUNCE_WAIT "2"
#undef  INET_IPAIP_ANNOUNCE_NUM
#define INET_IPAIP_ANNOUNCE_NUM "2"
#undef  INET_IPAIP_ANNOUNCE_INTERVAL
#define INET_IPAIP_ANNOUNCE_INTERVAL "2"
#undef  INET_IPAIP_MAX_CONFLICTS
#define INET_IPAIP_MAX_CONFLICTS "10"
#undef  INET_IPAIP_RATE_LIMIT_INTERVAL
#define INET_IPAIP_RATE_LIMIT_INTERVAL "60"
#undef  INET_IPAIP_DEFEND_INTERVAL
#define INET_IPAIP_DEFEND_INTERVAL "10"
#undef  INET_ENABLE_PROXY_ARP
#define INET_ENABLE_PROXY_ARP "0"
#undef  INET_AUTO_PROXY_ARP
#define INET_AUTO_PROXY_ARP "0"
#undef  INET_IFLIST_ENABLE_PROXY_ARP
#define INET_IFLIST_ENABLE_PROXY_ARP ""
#undef  INET_IFLIST_AUTO_PROXY_ARP
#define INET_IFLIST_AUTO_PROXY_ARP ""
#undef  RADVD_IFNAME_LIST
#define RADVD_IFNAME_LIST ""
#undef  RADVD_IFLIST_ADV_MANAGED_FLAG
#define RADVD_IFLIST_ADV_MANAGED_FLAG ""
#undef  RADVD_IFLIST_ADV_OTHER_CONFIG_FLAG
#define RADVD_IFLIST_ADV_OTHER_CONFIG_FLAG ""
#undef  RADVD_IFLIST_ADV_LINK_MTU
#define RADVD_IFLIST_ADV_LINK_MTU ""
#undef  RADVD_IFLIST_ADV_REACHABLE_TIME
#define RADVD_IFLIST_ADV_REACHABLE_TIME ""
#undef  RADVD_IFLIST_ADV_RETRANS_TIMER
#define RADVD_IFLIST_ADV_RETRANS_TIMER ""
#undef  RADVD_IFLIST_ADV_CUR_HOP_LIMIT
#define RADVD_IFLIST_ADV_CUR_HOP_LIMIT ""
#undef  RADVD_IFLIST_ADV_HA_FLAG
#define RADVD_IFLIST_ADV_HA_FLAG ""
#undef  RADVD_IFLIST_ADV_INTERVAL_OPT
#define RADVD_IFLIST_ADV_INTERVAL_OPT ""
#undef  RADVD_IFLIST_ADV_HA_OPT
#define RADVD_IFLIST_ADV_HA_OPT ""
#undef  RADVD_IFLIST_HA_OPT_LIFETIME
#define RADVD_IFLIST_HA_OPT_LIFETIME ""
#undef  RADVD_IFLIST_HA_OPT_PREFERENCE
#define RADVD_IFLIST_HA_OPT_PREFERENCE ""
#undef  RADVD_IFLIST_MIN_RTR_ADV_INTERVAL
#define RADVD_IFLIST_MIN_RTR_ADV_INTERVAL ""
#undef  RADVD_IFLIST_MAX_RTR_ADV_INTERVAL
#define RADVD_IFLIST_MAX_RTR_ADV_INTERVAL ""
#undef  RADVD_IFLIST_ADV_DEFAULT_LIFETIME
#define RADVD_IFLIST_ADV_DEFAULT_LIFETIME ""
#undef  RADVD_IFLIST_ADV_PREFIX
#define RADVD_IFLIST_ADV_PREFIX ""
#undef  RADVD_IFLIST_PREFIX
#define RADVD_IFLIST_PREFIX ""
#undef  RADVD_IFLIST_MIN_DELAY_BETWEEN_RAS
#define RADVD_IFLIST_MIN_DELAY_BETWEEN_RAS ""
#undef  RADVD_IFLIST_PREFIX_ADV_ONLINK_FLAG
#define RADVD_IFLIST_PREFIX_ADV_ONLINK_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_AUTONOMOUS_FLAG
#define RADVD_IFLIST_PREFIX_ADV_AUTONOMOUS_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_RTR_ADDR_FLAG
#define RADVD_IFLIST_PREFIX_ADV_RTR_ADDR_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME
#define RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME ""
#undef  RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME
#define RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME ""
#undef  IPNET_MAX_INPUT_PKTS
#define IPNET_MAX_INPUT_PKTS 32
#undef  IPNET_REASSEMBLY_TIMEOUT
#define IPNET_REASSEMBLY_TIMEOUT 15
#undef  IPNET_CACHE_BUFSIZE
#define IPNET_CACHE_BUFSIZE 0
#undef  INET_MIN_MTU_SIZE
#define INET_MIN_MTU_SIZE 68
#undef  INET_BASE_HOP_LIMIT
#define INET_BASE_HOP_LIMIT "64"
#undef  INET_MAX_PKTS_PENDING
#define INET_MAX_PKTS_PENDING "3"
#undef  INET_MAX_UNICAST_SOLICIT
#define INET_MAX_UNICAST_SOLICIT "1"
#undef  INET_MAX_MULTICAST_SOLICIT
#define INET_MAX_MULTICAST_SOLICIT "9"
#undef  INET_MAX_APP_SOLICIT
#define INET_MAX_APP_SOLICIT "1"
#undef  INET_BASE_REACHABLE_TIME
#define INET_BASE_REACHABLE_TIME "30"
#undef  INET_BASE_RETRANSMIT_TIME
#define INET_BASE_RETRANSMIT_TIME "1"
#undef  INET_DELAY_FIRST_PROBE_TIME
#define INET_DELAY_FIRST_PROBE_TIME "5"
#undef  INET_NBR_CACHE_TO_LIVE_TIME
#define INET_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET_DST_CACHE_TO_LIVE_TIME
#define INET_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET_ICMP_RATE_LIMIT_BUCKET_SIZE "100"
#undef  INET_ICMP_RATE_LIMIT_INTERVAL
#define INET_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET_ICMP_REDIRECT_SEND
#define INET_ICMP_REDIRECT_SEND "2"
#undef  INET_ICMP_REDIRECT_RECEIVE
#define INET_ICMP_REDIRECT_RECEIVE "1"
#undef  INET_ICMP_IGNORE_ECHO_REQ
#define INET_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET_ICMP_IGNORE_TIMESTAMP_REQ
#define INET_ICMP_IGNORE_TIMESTAMP_REQ "0"
#undef  INET_ICMP_SEND_TIME_EXCEEDED
#define INET_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET_ICMP_SEND_DST_UNREACHABLE
#define INET_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET6_MIN_MTU_SIZE
#define INET6_MIN_MTU_SIZE 1280
#undef  INET6_BASE_HOP_LIMIT
#define INET6_BASE_HOP_LIMIT "64"
#undef  INET6_MAX_PKTS_PENDING
#define INET6_MAX_PKTS_PENDING "3"
#undef  INET6_MAX_UNICAST_SOLICIT
#define INET6_MAX_UNICAST_SOLICIT "3"
#undef  INET6_MAX_MULTICAST_SOLICIT
#define INET6_MAX_MULTICAST_SOLICIT "0"
#undef  INET6_MAX_APP_SOLICIT
#define INET6_MAX_APP_SOLICIT "1"
#undef  INET6_DAD_TRANSMITS
#define INET6_DAD_TRANSMITS "1"
#undef  INET6_BASE_REACHABLE_TIME
#define INET6_BASE_REACHABLE_TIME "30"
#undef  INET6_BASE_RETRANSMIT_TIME
#define INET6_BASE_RETRANSMIT_TIME "1"
#undef  INET6_DELAY_FIRST_PROBE_TIME
#define INET6_DELAY_FIRST_PROBE_TIME "5"
#undef  INET6_NBR_CACHE_TO_LIVE_TIME
#define INET6_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET6_DST_CACHE_TO_LIVE_TIME
#define INET6_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET6_ROUTER_LIFETIME
#define INET6_ROUTER_LIFETIME "1800"
#undef  INET6_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET6_ICMP_RATE_LIMIT_BUCKET_SIZE "100"
#undef  INET6_ICMP_RATE_LIMIT_INTERVAL
#define INET6_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET6_ICMP_REDIRECT_SEND
#define INET6_ICMP_REDIRECT_SEND "2"
#undef  INET6_ICMP_REDIRECT_RECEIVE
#define INET6_ICMP_REDIRECT_RECEIVE "1"
#undef  INET6_ICMP_IGNORE_ECHO_REQ
#define INET6_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET6_ICMP_SEND_TIME_EXCEEDED
#define INET6_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET6_ICMP_SEND_DST_UNREACHABLE
#define INET6_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET6_ACCEPT_RTADV
#define INET6_ACCEPT_RTADV "1"
#undef  INET6_AUTO_CONFIG
#define INET6_AUTO_CONFIG "1"
#undef  INET6_RTHDR0
#define INET6_RTHDR0 "0"
#undef  TCP_CONN_TIMEOUT
#define TCP_CONN_TIMEOUT "30"
#undef  TCP_MAX_RETRANSMITS
#define TCP_MAX_RETRANSMITS "10"
#undef  TCP_MSL
#define TCP_MSL "30"
#undef  TCP_MAX_MSS
#define TCP_MAX_MSS "0"
#undef  TCP_USE_TIMESTAMP
#define TCP_USE_TIMESTAMP "0"
#undef  TCP_USE_RFC1122_URGENT_DATA
#define TCP_USE_RFC1122_URGENT_DATA "0"
#undef  TCP_SEGMENT_MULTIPLIER
#define TCP_SEGMENT_MULTIPLIER "2"
#undef  IPNET_SOCK_MAX
#define IPNET_SOCK_MAX 1024
#undef  IPNET_SOCK_ANON_PORT_MIN
#define IPNET_SOCK_ANON_PORT_MIN "49152"
#undef  IPNET_SOCK_ANON_PORT_MAX
#define IPNET_SOCK_ANON_PORT_MAX "65535"
#undef  IPNET_SOCK_DEFAULT_SEND_BUFSIZE
#define IPNET_SOCK_DEFAULT_SEND_BUFSIZE "10000"
#undef  IPNET_SOCK_DEFAULT_RECV_BUFSIZE
#define IPNET_SOCK_DEFAULT_RECV_BUFSIZE "10000"
#undef  IPNET_SOCK_ADDR_NOTIFY
#define IPNET_SOCK_ADDR_NOTIFY "1"

#endif /* INCprjParamsh */
